DROP DATABASE IF EXISTS `ref_data`;
CREATE DATABASE `ref_data`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE mysql;
-- CREATE USER 'aijax'@'%' IDENTIFIED BY 'aijax';
GRANT ALL PRIVILEGES ON *.* TO 'aijax'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;